// SDL3 Keycode and Scancode Bindings
// Complete key mappings and constants

const core = @import("core.zig");

// Keycode and scancode types
pub const SDL_Keycode = core.SDL_Keycode;
pub const SDL_Scancode = core.SDL_Scancode;

// === SDL Scan codes ===
// These values are from usage page 0x07 (USB keyboard page)
pub const SDL_SCANCODE_UNKNOWN = 0;

// Usage page 0x07
pub const SDL_SCANCODE_A = 4;
pub const SDL_SCANCODE_B = 5;
pub const SDL_SCANCODE_C = 6;
pub const SDL_SCANCODE_D = 7;
pub const SDL_SCANCODE_E = 8;
pub const SDL_SCANCODE_F = 9;
pub const SDL_SCANCODE_G = 10;
pub const SDL_SCANCODE_H = 11;
pub const SDL_SCANCODE_I = 12;
pub const SDL_SCANCODE_J = 13;
pub const SDL_SCANCODE_K = 14;
pub const SDL_SCANCODE_L = 15;
pub const SDL_SCANCODE_M = 16;
pub const SDL_SCANCODE_N = 17;
pub const SDL_SCANCODE_O = 18;
pub const SDL_SCANCODE_P = 19;
pub const SDL_SCANCODE_Q = 20;
pub const SDL_SCANCODE_R = 21;
pub const SDL_SCANCODE_S = 22;
pub const SDL_SCANCODE_T = 23;
pub const SDL_SCANCODE_U = 24;
pub const SDL_SCANCODE_V = 25;
pub const SDL_SCANCODE_W = 26;
pub const SDL_SCANCODE_X = 27;
pub const SDL_SCANCODE_Y = 28;
pub const SDL_SCANCODE_Z = 29;

pub const SDL_SCANCODE_1 = 30;
pub const SDL_SCANCODE_2 = 31;
pub const SDL_SCANCODE_3 = 32;
pub const SDL_SCANCODE_4 = 33;
pub const SDL_SCANCODE_5 = 34;
pub const SDL_SCANCODE_6 = 35;
pub const SDL_SCANCODE_7 = 36;
pub const SDL_SCANCODE_8 = 37;
pub const SDL_SCANCODE_9 = 38;
pub const SDL_SCANCODE_0 = 39;

pub const SDL_SCANCODE_RETURN = 40;
pub const SDL_SCANCODE_ESCAPE = 41;
pub const SDL_SCANCODE_BACKSPACE = 42;
pub const SDL_SCANCODE_TAB = 43;
pub const SDL_SCANCODE_SPACE = 44;

pub const SDL_SCANCODE_MINUS = 45;
pub const SDL_SCANCODE_EQUALS = 46;
pub const SDL_SCANCODE_LEFTBRACKET = 47;
pub const SDL_SCANCODE_RIGHTBRACKET = 48;
pub const SDL_SCANCODE_BACKSLASH = 49;
pub const SDL_SCANCODE_NONUSHASH = 50;
pub const SDL_SCANCODE_SEMICOLON = 51;
pub const SDL_SCANCODE_APOSTROPHE = 52;
pub const SDL_SCANCODE_GRAVE = 53;
pub const SDL_SCANCODE_COMMA = 54;
pub const SDL_SCANCODE_PERIOD = 55;
pub const SDL_SCANCODE_SLASH = 56;

pub const SDL_SCANCODE_CAPSLOCK = 57;

pub const SDL_SCANCODE_F1 = 58;
pub const SDL_SCANCODE_F2 = 59;
pub const SDL_SCANCODE_F3 = 60;
pub const SDL_SCANCODE_F4 = 61;
pub const SDL_SCANCODE_F5 = 62;
pub const SDL_SCANCODE_F6 = 63;
pub const SDL_SCANCODE_F7 = 64;
pub const SDL_SCANCODE_F8 = 65;
pub const SDL_SCANCODE_F9 = 66;
pub const SDL_SCANCODE_F10 = 67;
pub const SDL_SCANCODE_F11 = 68;
pub const SDL_SCANCODE_F12 = 69;

pub const SDL_SCANCODE_PRINTSCREEN = 70;
pub const SDL_SCANCODE_SCROLLLOCK = 71;
pub const SDL_SCANCODE_PAUSE = 72;
pub const SDL_SCANCODE_INSERT = 73;
pub const SDL_SCANCODE_HOME = 74;
pub const SDL_SCANCODE_PAGEUP = 75;
pub const SDL_SCANCODE_DELETE = 76;
pub const SDL_SCANCODE_END = 77;
pub const SDL_SCANCODE_PAGEDOWN = 78;
pub const SDL_SCANCODE_RIGHT = 79;
pub const SDL_SCANCODE_LEFT = 80;
pub const SDL_SCANCODE_DOWN = 81;
pub const SDL_SCANCODE_UP = 82;

pub const SDL_SCANCODE_NUMLOCKCLEAR = 83;
pub const SDL_SCANCODE_KP_DIVIDE = 84;
pub const SDL_SCANCODE_KP_MULTIPLY = 85;
pub const SDL_SCANCODE_KP_MINUS = 86;
pub const SDL_SCANCODE_KP_PLUS = 87;
pub const SDL_SCANCODE_KP_ENTER = 88;
pub const SDL_SCANCODE_KP_1 = 89;
pub const SDL_SCANCODE_KP_2 = 90;
pub const SDL_SCANCODE_KP_3 = 91;
pub const SDL_SCANCODE_KP_4 = 92;
pub const SDL_SCANCODE_KP_5 = 93;
pub const SDL_SCANCODE_KP_6 = 94;
pub const SDL_SCANCODE_KP_7 = 95;
pub const SDL_SCANCODE_KP_8 = 96;
pub const SDL_SCANCODE_KP_9 = 97;
pub const SDL_SCANCODE_KP_0 = 98;
pub const SDL_SCANCODE_KP_PERIOD = 99;

pub const SDL_SCANCODE_NONUSBACKSLASH = 100;
pub const SDL_SCANCODE_APPLICATION = 101;
pub const SDL_SCANCODE_POWER = 102;
pub const SDL_SCANCODE_KP_EQUALS = 103;
pub const SDL_SCANCODE_F13 = 104;
pub const SDL_SCANCODE_F14 = 105;
pub const SDL_SCANCODE_F15 = 106;
pub const SDL_SCANCODE_F16 = 107;
pub const SDL_SCANCODE_F17 = 108;
pub const SDL_SCANCODE_F18 = 109;
pub const SDL_SCANCODE_F19 = 110;
pub const SDL_SCANCODE_F20 = 111;
pub const SDL_SCANCODE_F21 = 112;
pub const SDL_SCANCODE_F22 = 113;
pub const SDL_SCANCODE_F23 = 114;
pub const SDL_SCANCODE_F24 = 115;

pub const SDL_SCANCODE_EXECUTE = 116;
pub const SDL_SCANCODE_HELP = 117;
pub const SDL_SCANCODE_MENU = 118;
pub const SDL_SCANCODE_SELECT = 119;
pub const SDL_SCANCODE_STOP = 120;
pub const SDL_SCANCODE_AGAIN = 121;
pub const SDL_SCANCODE_UNDO = 122;
pub const SDL_SCANCODE_CUT = 123;
pub const SDL_SCANCODE_COPY = 124;
pub const SDL_SCANCODE_PASTE = 125;
pub const SDL_SCANCODE_FIND = 126;
pub const SDL_SCANCODE_MUTE = 127;
pub const SDL_SCANCODE_VOLUMEUP = 128;
pub const SDL_SCANCODE_VOLUMEDOWN = 129;

pub const SDL_SCANCODE_KP_COMMA = 133;
pub const SDL_SCANCODE_KP_EQUALSAS400 = 134;

pub const SDL_SCANCODE_INTERNATIONAL1 = 135;
pub const SDL_SCANCODE_INTERNATIONAL2 = 136;
pub const SDL_SCANCODE_INTERNATIONAL3 = 137;
pub const SDL_SCANCODE_INTERNATIONAL4 = 138;
pub const SDL_SCANCODE_INTERNATIONAL5 = 139;
pub const SDL_SCANCODE_INTERNATIONAL6 = 140;
pub const SDL_SCANCODE_INTERNATIONAL7 = 141;
pub const SDL_SCANCODE_INTERNATIONAL8 = 142;
pub const SDL_SCANCODE_INTERNATIONAL9 = 143;
pub const SDL_SCANCODE_LANG1 = 144;
pub const SDL_SCANCODE_LANG2 = 145;
pub const SDL_SCANCODE_LANG3 = 146;
pub const SDL_SCANCODE_LANG4 = 147;
pub const SDL_SCANCODE_LANG5 = 148;
pub const SDL_SCANCODE_LANG6 = 149;
pub const SDL_SCANCODE_LANG7 = 150;
pub const SDL_SCANCODE_LANG8 = 151;
pub const SDL_SCANCODE_LANG9 = 152;

pub const SDL_SCANCODE_ALTERASE = 153;
pub const SDL_SCANCODE_SYSREQ = 154;
pub const SDL_SCANCODE_CANCEL = 155;
pub const SDL_SCANCODE_CLEAR = 156;
pub const SDL_SCANCODE_PRIOR = 157;
pub const SDL_SCANCODE_RETURN2 = 158;
pub const SDL_SCANCODE_SEPARATOR = 159;
pub const SDL_SCANCODE_OUT = 160;
pub const SDL_SCANCODE_OPER = 161;
pub const SDL_SCANCODE_CLEARAGAIN = 162;
pub const SDL_SCANCODE_CRSEL = 163;
pub const SDL_SCANCODE_EXSEL = 164;

pub const SDL_SCANCODE_KP_00 = 176;
pub const SDL_SCANCODE_KP_000 = 177;
pub const SDL_SCANCODE_THOUSANDSSEPARATOR = 178;
pub const SDL_SCANCODE_DECIMALSEPARATOR = 179;
pub const SDL_SCANCODE_CURRENCYUNIT = 180;
pub const SDL_SCANCODE_CURRENCYSUBUNIT = 181;
pub const SDL_SCANCODE_KP_LEFTPAREN = 182;
pub const SDL_SCANCODE_KP_RIGHTPAREN = 183;
pub const SDL_SCANCODE_KP_LEFTBRACE = 184;
pub const SDL_SCANCODE_KP_RIGHTBRACE = 185;
pub const SDL_SCANCODE_KP_TAB = 186;
pub const SDL_SCANCODE_KP_BACKSPACE = 187;
pub const SDL_SCANCODE_KP_A = 188;
pub const SDL_SCANCODE_KP_B = 189;
pub const SDL_SCANCODE_KP_C = 190;
pub const SDL_SCANCODE_KP_D = 191;
pub const SDL_SCANCODE_KP_E = 192;
pub const SDL_SCANCODE_KP_F = 193;
pub const SDL_SCANCODE_KP_XOR = 194;
pub const SDL_SCANCODE_KP_POWER = 195;
pub const SDL_SCANCODE_KP_PERCENT = 196;
pub const SDL_SCANCODE_KP_LESS = 197;
pub const SDL_SCANCODE_KP_GREATER = 198;
pub const SDL_SCANCODE_KP_AMPERSAND = 199;
pub const SDL_SCANCODE_KP_DBLAMPERSAND = 200;
pub const SDL_SCANCODE_KP_VERTICALBAR = 201;
pub const SDL_SCANCODE_KP_DBLVERTICALBAR = 202;
pub const SDL_SCANCODE_KP_COLON = 203;
pub const SDL_SCANCODE_KP_HASH = 204;
pub const SDL_SCANCODE_KP_SPACE = 205;
pub const SDL_SCANCODE_KP_AT = 206;
pub const SDL_SCANCODE_KP_EXCLAM = 207;
pub const SDL_SCANCODE_KP_MEMSTORE = 208;
pub const SDL_SCANCODE_KP_MEMRECALL = 209;
pub const SDL_SCANCODE_KP_MEMCLEAR = 210;
pub const SDL_SCANCODE_KP_MEMADD = 211;
pub const SDL_SCANCODE_KP_MEMSUBTRACT = 212;
pub const SDL_SCANCODE_KP_MEMMULTIPLY = 213;
pub const SDL_SCANCODE_KP_MEMDIVIDE = 214;
pub const SDL_SCANCODE_KP_PLUSMINUS = 215;
pub const SDL_SCANCODE_KP_CLEAR = 216;
pub const SDL_SCANCODE_KP_CLEARENTRY = 217;
pub const SDL_SCANCODE_KP_BINARY = 218;
pub const SDL_SCANCODE_KP_OCTAL = 219;
pub const SDL_SCANCODE_KP_DECIMAL = 220;
pub const SDL_SCANCODE_KP_HEXADECIMAL = 221;

pub const SDL_SCANCODE_LCTRL = 224;
pub const SDL_SCANCODE_LSHIFT = 225;
pub const SDL_SCANCODE_LALT = 226;
pub const SDL_SCANCODE_LGUI = 227;
pub const SDL_SCANCODE_RCTRL = 228;
pub const SDL_SCANCODE_RSHIFT = 229;
pub const SDL_SCANCODE_RALT = 230;
pub const SDL_SCANCODE_RGUI = 231;

pub const SDL_SCANCODE_MODE = 257;

pub const SDL_SCANCODE_AUDIONEXT = 258;
pub const SDL_SCANCODE_AUDIOPREV = 259;
pub const SDL_SCANCODE_AUDIOSTOP = 260;
pub const SDL_SCANCODE_AUDIOPLAY = 261;
pub const SDL_SCANCODE_AUDIOMUTE = 262;
pub const SDL_SCANCODE_MEDIASELECT = 263;
pub const SDL_SCANCODE_WWW = 264;
pub const SDL_SCANCODE_MAIL = 265;
pub const SDL_SCANCODE_CALCULATOR = 266;
pub const SDL_SCANCODE_COMPUTER = 267;
pub const SDL_SCANCODE_AC_SEARCH = 268;
pub const SDL_SCANCODE_AC_HOME = 269;
pub const SDL_SCANCODE_AC_BACK = 270;
pub const SDL_SCANCODE_AC_FORWARD = 271;
pub const SDL_SCANCODE_AC_STOP = 272;
pub const SDL_SCANCODE_AC_REFRESH = 273;
pub const SDL_SCANCODE_AC_BOOKMARKS = 274;

pub const SDL_SCANCODE_BRIGHTNESSDOWN = 275;
pub const SDL_SCANCODE_BRIGHTNESSUP = 276;
pub const SDL_SCANCODE_DISPLAYSWITCH = 277;
pub const SDL_SCANCODE_KBDILLUMTOGGLE = 278;
pub const SDL_SCANCODE_KBDILLUMDOWN = 279;
pub const SDL_SCANCODE_KBDILLUMUP = 280;
pub const SDL_SCANCODE_EJECT = 281;
pub const SDL_SCANCODE_SLEEP = 282;

pub const SDL_SCANCODE_APP1 = 283;
pub const SDL_SCANCODE_APP2 = 284;

pub const SDL_NUM_SCANCODES = 285;

// === SDL Key codes ===
// Keycode masks and macros
pub const SDLK_SCANCODE_MASK = 1 << 30;
pub const SDLK_EXTENDED_MASK = 1 << 29;

// Keycode conversion function
pub fn SDL_SCANCODE_TO_KEYCODE(scancode: SDL_Scancode) SDL_Keycode {
    return @as(SDL_Keycode, scancode) | SDLK_SCANCODE_MASK;
}

// Printable character keycodes
pub const SDLK_UNKNOWN = 0;
pub const SDLK_RETURN = '\r';
pub const SDLK_ESCAPE = '\x1B';
pub const SDLK_BACKSPACE = '\x08';
pub const SDLK_TAB = '\t';
pub const SDLK_SPACE = ' ';
pub const SDLK_EXCLAIM = '!';
pub const SDLK_DBLAPOSTROPHE = '"';
pub const SDLK_HASH = '#';
pub const SDLK_DOLLAR = '$';
pub const SDLK_PERCENT = '%';
pub const SDLK_AMPERSAND = '&';
pub const SDLK_APOSTROPHE = '\'';
pub const SDLK_LEFTPAREN = '(';
pub const SDLK_RIGHTPAREN = ')';
pub const SDLK_ASTERISK = '*';
pub const SDLK_PLUS = '+';
pub const SDLK_COMMA = ',';
pub const SDLK_MINUS = '-';
pub const SDLK_PERIOD = '.';
pub const SDLK_SLASH = '/';
pub const SDLK_0 = '0';
pub const SDLK_1 = '1';
pub const SDLK_2 = '2';
pub const SDLK_3 = '3';
pub const SDLK_4 = '4';
pub const SDLK_5 = '5';
pub const SDLK_6 = '6';
pub const SDLK_7 = '7';
pub const SDLK_8 = '8';
pub const SDLK_9 = '9';
pub const SDLK_COLON = ':';
pub const SDLK_SEMICOLON = ';';
pub const SDLK_LESS = '<';
pub const SDLK_EQUALS = '=';
pub const SDLK_GREATER = '>';
pub const SDLK_QUESTION = '?';
pub const SDLK_AT = '@';
pub const SDLK_LEFTBRACKET = '[';
pub const SDLK_BACKSLASH = '\\';
pub const SDLK_RIGHTBRACKET = ']';
pub const SDLK_CARET = '^';
pub const SDLK_UNDERSCORE = '_';
pub const SDLK_BACKQUOTE = '`';
pub const SDLK_a = 'a';
pub const SDLK_b = 'b';
pub const SDLK_c = 'c';
pub const SDLK_d = 'd';
pub const SDLK_e = 'e';
pub const SDLK_f = 'f';
pub const SDLK_g = 'g';
pub const SDLK_h = 'h';
pub const SDLK_i = 'i';
pub const SDLK_j = 'j';
pub const SDLK_k = 'k';
pub const SDLK_l = 'l';
pub const SDLK_m = 'm';
pub const SDLK_n = 'n';
pub const SDLK_o = 'o';
pub const SDLK_p = 'p';
pub const SDLK_q = 'q';
pub const SDLK_r = 'r';
pub const SDLK_s = 's';
pub const SDLK_t = 't';
pub const SDLK_u = 'u';
pub const SDLK_v = 'v';
pub const SDLK_w = 'w';
pub const SDLK_x = 'x';
pub const SDLK_y = 'y';
pub const SDLK_z = 'z';
pub const SDLK_CAPSLOCK = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK);

// Function keys
pub const SDLK_F1 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1);
pub const SDLK_F2 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2);
pub const SDLK_F3 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3);
pub const SDLK_F4 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4);
pub const SDLK_F5 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5);
pub const SDLK_F6 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6);
pub const SDLK_F7 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7);
pub const SDLK_F8 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8);
pub const SDLK_F9 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9);
pub const SDLK_F10 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10);
pub const SDLK_F11 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11);
pub const SDLK_F12 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12);

// Arrow keys and navigation
pub const SDLK_PRINTSCREEN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN);
pub const SDLK_SCROLLLOCK = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK);
pub const SDLK_PAUSE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE);
pub const SDLK_INSERT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT);
pub const SDLK_HOME = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME);
pub const SDLK_PAGEUP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP);
pub const SDLK_DELETE = '\x7F';
pub const SDLK_END = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END);
pub const SDLK_PAGEDOWN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN);
pub const SDLK_RIGHT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT);
pub const SDLK_LEFT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT);
pub const SDLK_DOWN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN);
pub const SDLK_UP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP);

// Keypad keys
pub const SDLK_NUMLOCKCLEAR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR);
pub const SDLK_KP_DIVIDE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE);
pub const SDLK_KP_MULTIPLY = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY);
pub const SDLK_KP_MINUS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS);
pub const SDLK_KP_PLUS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS);
pub const SDLK_KP_ENTER = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER);
pub const SDLK_KP_1 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1);
pub const SDLK_KP_2 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2);
pub const SDLK_KP_3 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3);
pub const SDLK_KP_4 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4);
pub const SDLK_KP_5 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5);
pub const SDLK_KP_6 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6);
pub const SDLK_KP_7 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7);
pub const SDLK_KP_8 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8);
pub const SDLK_KP_9 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9);
pub const SDLK_KP_0 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0);
pub const SDLK_KP_PERIOD = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD);

// International and multimedia keys
pub const SDLK_APPLICATION = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION);
pub const SDLK_POWER = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER);
pub const SDLK_KP_EQUALS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS);
pub const SDLK_F13 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F13);
pub const SDLK_F14 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F14);
pub const SDLK_F15 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F15);
pub const SDLK_F16 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F16);
pub const SDLK_F17 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F17);
pub const SDLK_F18 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F18);
pub const SDLK_F19 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F19);
pub const SDLK_F20 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F20);
pub const SDLK_F21 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F21);
pub const SDLK_F22 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F22);
pub const SDLK_F23 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F23);
pub const SDLK_F24 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F24);
pub const SDLK_EXECUTE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXECUTE);
pub const SDLK_HELP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HELP);
pub const SDLK_MENU = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MENU);
pub const SDLK_SELECT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SELECT);
pub const SDLK_STOP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_STOP);
pub const SDLK_AGAIN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN);
pub const SDLK_UNDO = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UNDO);
pub const SDLK_CUT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT);
pub const SDLK_COPY = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY);
pub const SDLK_PASTE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE);
pub const SDLK_FIND = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_FIND);
pub const SDLK_MUTE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE);
pub const SDLK_VOLUMEUP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP);
pub const SDLK_VOLUMEDOWN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN);

// Additional keypad keys
pub const SDLK_KP_COMMA = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA);
pub const SDLK_KP_EQUALSAS400 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400);

// Language-specific keys
pub const SDLK_ALTERASE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE);
pub const SDLK_SYSREQ = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ);
pub const SDLK_CANCEL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CANCEL);
pub const SDLK_CLEAR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEAR);
pub const SDLK_PRIOR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRIOR);
pub const SDLK_RETURN2 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2);
pub const SDLK_SEPARATOR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SEPARATOR);
pub const SDLK_OUT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT);
pub const SDLK_OPER = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER);
pub const SDLK_CLEARAGAIN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN);
pub const SDLK_CRSEL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL);
pub const SDLK_EXSEL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL);

// Extended keypad keys
pub const SDLK_KP_00 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00);
pub const SDLK_KP_000 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000);
pub const SDLK_THOUSANDSSEPARATOR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR);
pub const SDLK_DECIMALSEPARATOR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR);
pub const SDLK_CURRENCYUNIT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT);
pub const SDLK_CURRENCYSUBUNIT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT);
pub const SDLK_KP_LEFTPAREN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN);
pub const SDLK_KP_RIGHTPAREN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN);
pub const SDLK_KP_LEFTBRACE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE);
pub const SDLK_KP_RIGHTBRACE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE);
pub const SDLK_KP_TAB = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_TAB);
pub const SDLK_KP_BACKSPACE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE);
pub const SDLK_KP_A = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A);
pub const SDLK_KP_B = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B);
pub const SDLK_KP_C = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C);
pub const SDLK_KP_D = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D);
pub const SDLK_KP_E = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E);
pub const SDLK_KP_F = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F);
pub const SDLK_KP_XOR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR);
pub const SDLK_KP_POWER = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER);
pub const SDLK_KP_PERCENT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT);
pub const SDLK_KP_LESS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS);
pub const SDLK_KP_GREATER = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER);
pub const SDLK_KP_AMPERSAND = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND);
pub const SDLK_KP_DBLAMPERSAND = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND);
pub const SDLK_KP_VERTICALBAR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR);
pub const SDLK_KP_DBLVERTICALBAR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR);
pub const SDLK_KP_COLON = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON);
pub const SDLK_KP_HASH = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH);
pub const SDLK_KP_SPACE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE);
pub const SDLK_KP_AT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT);
pub const SDLK_KP_EXCLAM = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM);
pub const SDLK_KP_MEMSTORE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE);
pub const SDLK_KP_MEMRECALL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL);
pub const SDLK_KP_MEMCLEAR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR);
pub const SDLK_KP_MEMADD = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD);
pub const SDLK_KP_MEMSUBTRACT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT);
pub const SDLK_KP_MEMMULTIPLY = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY);
pub const SDLK_KP_MEMDIVIDE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE);
pub const SDLK_KP_PLUSMINUS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS);
pub const SDLK_KP_CLEAR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR);
pub const SDLK_KP_CLEARENTRY = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY);
pub const SDLK_KP_BINARY = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY);
pub const SDLK_KP_OCTAL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL);
pub const SDLK_KP_DECIMAL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL);
pub const SDLK_KP_HEXADECIMAL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL);

// Modifier keys
pub const SDLK_LCTRL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL);
pub const SDLK_LSHIFT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT);
pub const SDLK_LALT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT);
pub const SDLK_LGUI = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI);
pub const SDLK_RCTRL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL);
pub const SDLK_RSHIFT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT);
pub const SDLK_RALT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT);
pub const SDLK_RGUI = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI);

// Mode and media keys
pub const SDLK_MODE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MODE);
pub const SDLK_AUDIONEXT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIONEXT);
pub const SDLK_AUDIOPREV = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOPREV);
pub const SDLK_AUDIOSTOP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOSTOP);
pub const SDLK_AUDIOPLAY = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOPLAY);
pub const SDLK_AUDIOMUTE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOMUTE);
pub const SDLK_MEDIASELECT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIASELECT);
pub const SDLK_WWW = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WWW);
pub const SDLK_MAIL = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MAIL);
pub const SDLK_CALCULATOR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALCULATOR);
pub const SDLK_COMPUTER = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COMPUTER);
pub const SDLK_AC_SEARCH = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH);
pub const SDLK_AC_HOME = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME);
pub const SDLK_AC_BACK = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK);
pub const SDLK_AC_FORWARD = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD);
pub const SDLK_AC_STOP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP);
pub const SDLK_AC_REFRESH = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH);
pub const SDLK_AC_BOOKMARKS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS);

// System control keys
pub const SDLK_BRIGHTNESSDOWN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_BRIGHTNESSDOWN);
pub const SDLK_BRIGHTNESSUP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_BRIGHTNESSUP);
pub const SDLK_DISPLAYSWITCH = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DISPLAYSWITCH);
pub const SDLK_KBDILLUMTOGGLE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMTOGGLE);
pub const SDLK_KBDILLUMDOWN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMDOWN);
pub const SDLK_KBDILLUMUP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMUP);
pub const SDLK_EJECT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EJECT);
pub const SDLK_SLEEP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP);

// Application keys
pub const SDLK_APP1 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APP1);
pub const SDLK_APP2 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APP2);

// === Mouse Button Constants ===
// These are handled through mouse events but included for completeness
pub const SDL_BUTTON_LEFT = 1;
pub const SDL_BUTTON_MIDDLE = 2;
pub const SDL_BUTTON_RIGHT = 3;
pub const SDL_BUTTON_X1 = 4;
pub const SDL_BUTTON_X2 = 5;

// Mouse button masks
pub const SDL_BUTTON_LMASK = 1 << (SDL_BUTTON_LEFT - 1);
pub const SDL_BUTTON_MMASK = 1 << (SDL_BUTTON_MIDDLE - 1);
pub const SDL_BUTTON_RMASK = 1 << (SDL_BUTTON_RIGHT - 1);
pub const SDL_BUTTON_X1MASK = 1 << (SDL_BUTTON_X1 - 1);
pub const SDL_BUTTON_X2MASK = 1 << (SDL_BUTTON_X2 - 1);

// === Key Modifier constants ===
pub const KMOD_NONE = 0x0000;
pub const KMOD_LSHIFT = 0x0001;
pub const KMOD_RSHIFT = 0x0002;
pub const KMOD_LCTRL = 0x0040;
pub const KMOD_RCTRL = 0x0080;
pub const KMOD_LALT = 0x0100;
pub const KMOD_RALT = 0x0200;
pub const KMOD_LGUI = 0x0400;
pub const KMOD_RGUI = 0x0800;
pub const KMOD_NUM = 0x1000;
pub const KMOD_CAPS = 0x2000;
pub const KMOD_MODE = 0x4000;
pub const KMOD_SCROLL = 0x8000;

// Convenient combinations
pub const KMOD_SHIFT = KMOD_LSHIFT | KMOD_RSHIFT;
pub const KMOD_CTRL = KMOD_LCTRL | KMOD_RCTRL;
pub const KMOD_ALT = KMOD_LALT | KMOD_RALT;
pub const KMOD_GUI = KMOD_LGUI | KMOD_RGUI;

// === External SDL Functions ===
extern fn SDL_GetKeyFromName(name: [*:0]const u8) SDL_Keycode;
extern fn SDL_GetKeyName(key: SDL_Keycode) ?[*:0]const u8;
extern fn SDL_GetScancodeFromName(name: [*:0]const u8) SDL_Scancode;
extern fn SDL_GetScancodeName(scancode: SDL_Scancode) ?[*:0]const u8;
extern fn SDL_SetScancodeName(scancode: SDL_Scancode, name: [*:0]const u8) bool;

// Additional useful functions
extern fn SDL_GetKeyFromScancode(scancode: SDL_Scancode) SDL_Keycode;
extern fn SDL_GetScancodeFromKey(key: SDL_Keycode) SDL_Scancode;

// === Public API ===
pub const getKeyFromName = SDL_GetKeyFromName;
pub const getKeyName = SDL_GetKeyName;
pub const getScancodeFromName = SDL_GetScancodeFromName;
pub const getScancodeName = SDL_GetScancodeName;
pub const setScancodeName = SDL_SetScancodeName;
pub const getKeyFromScancode = SDL_GetKeyFromScancode;
pub const getScancodeFromKey = SDL_GetScancodeFromKey;

// === Utility Functions ===
/// Check if a keycode is printable (character)
pub fn isPrintable(keycode: SDL_Keycode) bool {
    return (keycode & SDLK_SCANCODE_MASK) == 0 and keycode >= 32 and keycode <= 126;
}

/// Check if a keycode represents a scancode
pub fn isScancodeKeycode(keycode: SDL_Keycode) bool {
    return (keycode & SDLK_SCANCODE_MASK) != 0;
}

/// Get the scancode from a keycode if it represents one
pub fn keycodeToScancode(keycode: SDL_Keycode) ?SDL_Scancode {
    if (isScancodeKeycode(keycode)) {
        return @intCast(keycode & ~SDLK_SCANCODE_MASK);
    }
    return null;
}
